spring:
  profiles:
    active: default # 环境
server:
  port: 8888 # 启动端口
  servlet:
    context-path: /slipper # 项目路径
  tomcat:
    uri-encoding: utf-8 # 编码
    connection-timeout: 5000ms # 连接超时

config:
  app-id:wxc22f095df911a8dd
  app-secret:da2e6fc9061ee6ea2597723eefeec074
  template-id:
  wechat-number:o-TSp5lMZ_jiMZbZlCrjqpGL_HKs,o-TSp5ieHEAJoh2-_8k-Ggtpg5v8
  birthday:2001-11-16
  city-code:{
        "cityName": "郴州",
        "province": "湖南",
        "cityPinyin": "chenzhou",
        "cityCode": "101250501"
    }
  constellation-key:
